"""Document-wide FP/FN evaluation of **GLiNER2** + the LLM judge on a single
plain-text document.

GLiNER2 counterpart of
:mod:`tests.integration.test_openmed_pii_text_document_with_judge`. It scans a
**dedicated** Confluence-like document
(``tests/resources/gliner2-pii-test-document.txt`` + its sidecar
``gliner2-pii-test-document.annotations.json``, generated by
``tests/resources/gliner2-fp-eval/_generate_text_document.py``) with the
GLiNER2 detector (the ``gliner2`` package), parametrized over the two
checkpoints under evaluation (``gliner2-large-v1`` and the PII fine-tune).

Scoping
-------

The document is assembled from the **24 evaluated GLiNER2 types** only (the
agreed privacy-filter subset), so every annotated line belongs to one of those
types — no out-of-list buckets. The document-wide scorer (reused from the
OpenMed sibling via :func:`_parse_document`) is **type-agnostic**: a detection
counts as a TP when it overlaps the annotated PII *value* on a TP line
(IoU >= 0.5) and as an FP elsewhere — the detector's own label is never
compared to the annotation's ``pii_type``.

Assertions (document-wide, per model)
-------------------------------------

Only ONE hard gate document-wide — recall-degradation is SOFT here (it is HARD
in the per-type harness):

* **HARD — judge must not worsen precision**: ``judged_fp_rate <=
  baseline_fp_rate``. The judge removes entities only, so a regression means it
  dropped TPs faster than FPs. Both checkpoints pass — the judge is a strong
  precision booster (it clears the large majority of GLiNER2's FPs).
* **SOFT (WARN) — recall degradation, absolute FP cap (0.10), recall floor
  (0.50)**. Document-wide recall/precision are distorted by the
  one-value-per-line annotation (GLiNER2 also surfaces real PII the sidecar
  doesn't list — e.g. extra expiry/CVV on a card line — which inflates both FP
  and apparent TP-loss) and by values the document frames as test/example data
  that the judge rightly discounts. So recall erosion here measures the
  fixture+detector interaction, not a judge safety defect, and is
  reported rather than gated.

Run (dedicated venv — see tests/resources/gliner2-fp-eval/README.md):

    .venv-gliner2/Scripts/python.exe -m pytest \\
        tests/integration/test_gliner2_pii_text_document_with_judge.py \\
        -v -s --log-cli-level=INFO --no-cov

Skipped automatically when the ``gliner2`` package is missing or LM Studio is
unreachable.
"""

from __future__ import annotations

import logging
import os
import time
from collections import defaultdict
from pathlib import Path
from typing import Dict, List

import pytest

# Document parser, metrics and matching utilities — reused verbatim from the
# OpenMed document-wide sibling (these are detector-agnostic). ``_parse_document``
# accepts explicit document/annotations paths so we point it at the dedicated
# GLiNER2 document below. We do NOT reuse the OpenMed GLOBAL_THRESHOLD (0.30) —
# this test owns its own detection threshold (see GLINER2_DOC_THRESHOLD).
from tests.integration.test_openmed_pii_text_document_with_judge import (
    IOU_MATCH_THRESHOLD,
    DocumentMetrics,
    _iou,
    _parse_document,
    _resolve_line_for_offset,
    _value_offsets_on_line,
)

# GLiNER2 wrapper + recalibrated budgets + guards from the per-type harness.
from tests.integration.test_gliner2_realistic_fp_evaluation_with_judge import (
    BASE_URL,
    GLINER2_MODEL_IDS,
    MAX_RECALL_DEGRADATION,
    MIN_RECALL,
    WARN_FP_RATE_WITH_JUDGE,
    _Gliner2Wrapper,
    _runtime,
)

from pii_detector.domain.entity.detector_source import DetectorSource

log = logging.getLogger("gliner2_text_doc_with_judge")


# Dedicated GLiNER2 document (24-type taxonomy), generated by
# tests/resources/gliner2-fp-eval/_generate_text_document.py. Unlike the OpenMed
# document, every annotated line belongs to one of the 24 evaluated GLiNER2
# types — no out-of-list buckets.
_RESOURCES_DIR = Path(__file__).resolve().parent.parent / "resources"
GLINER2_DOCUMENT_PATH = _RESOURCES_DIR / "gliner2-pii-test-document.txt"
GLINER2_ANNOTATIONS_PATH = _RESOURCES_DIR / "gliner2-pii-test-document.annotations.json"

# Detection threshold fed to GLiNER2 for the whole-document scan. Lowered to
# 0.15 (vs the OpenMed-doc 0.30) to recover baseline recall: GLiNER2 misses most
# TPs at the score floor, and the judge cleans up the extra false positives the
# lower threshold lets through. Env-overridable for a recall/precision sweep
# (e.g. LM_GLINER2_DOC_THRESHOLD=0.30).
GLINER2_DOC_THRESHOLD = float(os.getenv("LM_GLINER2_DOC_THRESHOLD", "0.15"))


pytestmark = [pytest.mark.integration, pytest.mark.slow]


# ---------------------------------------------------------------------------
# Fixtures (heavy: GLiNER2 model + judge)
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def parsed_document():
    scan_document, annotations, positions = _parse_document(
        GLINER2_DOCUMENT_PATH, GLINER2_ANNOTATIONS_PATH
    )
    log.info(
        "[setup] parsed %d annotated lines (%d TP / %d FP) — scan_document=%d chars",
        len(annotations),
        sum(1 for a in annotations if a.verdict == "TP"),
        sum(1 for a in annotations if a.verdict == "FP"),
        len(scan_document),
    )
    return scan_document, annotations, positions


@pytest.fixture(
    scope="module", params=GLINER2_MODEL_IDS, ids=lambda m: m.split("/")[-1]
)
def gliner2_detector(request) -> _Gliner2Wrapper:
    wrapper = _Gliner2Wrapper(request.param)
    wrapper.load()
    return wrapper


@pytest.fixture(scope="module")
def judge_validator():
    """Real ``LLMJudgeValidator`` auditing GLiNER-sourced entities.

    ``max_workers=1`` is mandatory here (not a tuning choice), exactly as in the
    OpenMed document-wide sibling: this test scans ONE big document, so a single
    ``filter()`` call submits all of the document's detections at once. LM
    Studio splits its context window across parallel slots; 3+ concurrent judge
    requests overflow a slot and return HTTP 400, which ``fail_open=True`` would
    silently swallow (keeping every entity and defeating the FP assertions).
    Serialising gives every call the full context window.
    """
    from pii_detector.infrastructure.validation.llm_validator import (
        LLMJudgeValidator,
    )

    log.info(
        "[setup] building LLMJudgeValidator(audit_sources={GLINER}, max_workers=1) on %s",
        BASE_URL,
    )
    validator = LLMJudgeValidator(
        base_url=BASE_URL,
        audit_sources={DetectorSource.GLINER},
        fail_open=True,
        max_workers=1,
    )
    try:
        yield validator
    finally:
        validator.shutdown()


# ---------------------------------------------------------------------------
# Main document-wide test (per model)
# ---------------------------------------------------------------------------


@_runtime
def test_Should_NotWorsenFpRate_When_JudgeIsAppliedOnGliner2PlainTextDocument(
    parsed_document, gliner2_detector, judge_validator
):
    """Scan the whole document with GLiNER2, run the judge, compare baseline vs
    judged metrics. Hard gates assert the judge's safety (no precision
    regression, bounded recall erosion); absolute FP/recall are SOFT signals.

    Every detection is logged with its line + KEPT/DROP + TP/FP; FP-survivors
    and TP-loss outcomes are promoted to WARNING.
    """
    scan_document, annotations, positions = parsed_document
    model_id = gliner2_detector.model_id
    annotation_by_line = {a.line_number: a for a in annotations}
    line_text_by_number = {a.line_number: a.text for a in annotations}

    # --- 1. GLiNER2 scan over the full document ------------------------
    log.info(
        "[scan|%s] running GLiNER2 on %d-char document (%d annotated lines) "
        "at threshold=%.2f",
        model_id, len(scan_document), len(annotations), GLINER2_DOC_THRESHOLD,
    )
    t0 = time.time()
    raw_entities = gliner2_detector.detect(scan_document, threshold=GLINER2_DOC_THRESHOLD)
    log.info(
        "[scan|%s] GLiNER2 produced %d entities in %.1fs",
        model_id, len(raw_entities), time.time() - t0,
    )

    # --- 2. Apply the LLM judge ----------------------------------------
    t0 = time.time()
    judged_entities = (
        judge_validator.filter(scan_document, raw_entities) if raw_entities else []
    )
    log.info(
        "[judge|%s] judged set: %d entities (out of %d baseline) in %.1fs",
        model_id, len(judged_entities), len(raw_entities), time.time() - t0,
    )
    judged_spans = {(e.start, e.end) for e in judged_entities}

    # --- 3. Per-entity verdict + structured logging --------------------
    metrics = DocumentMetrics()
    matched_tp_lines_baseline: set = set()
    matched_tp_lines_judged: set = set()

    for ent in raw_entities:
        line_pos = _resolve_line_for_offset(positions, ent.start, ent.end)
        if line_pos is None:
            continue  # detection outside any annotated line — not scored
        annotation = annotation_by_line[line_pos.line_number]
        line_text = line_text_by_number[line_pos.line_number]

        ground_truth = "FP"
        if annotation.verdict == "TP" and annotation.expected_value:
            for ex_start, ex_end in _value_offsets_on_line(
                line_text, line_pos, annotation.expected_value
            ):
                if _iou(ent.start, ent.end, ex_start, ex_end) >= IOU_MATCH_THRESHOLD:
                    ground_truth = "TP"
                    break

        action = "KEPT" if (ent.start, ent.end) in judged_spans else "DROP"
        pii_type = annotation.pii_type
        bucket = metrics.per_type[pii_type]

        if ground_truth == "TP":
            metrics.baseline_tp += 1
            bucket["b_tp"] += 1
            matched_tp_lines_baseline.add(line_pos.line_number)
            if action == "KEPT":
                metrics.judged_tp += 1
                bucket["j_tp"] += 1
                matched_tp_lines_judged.add(line_pos.line_number)
            else:
                metrics.judged_fn += 1
                bucket["j_fn"] += 1
                metrics.tp_loss.append(
                    (line_pos.line_number, pii_type,
                     scan_document[ent.start:ent.end], line_text[:200])
                )
        else:
            metrics.baseline_fp += 1
            bucket["b_fp"] += 1
            if action == "KEPT":
                metrics.judged_fp += 1
                bucket["j_fp"] += 1
                metrics.fp_survivors.append(
                    (line_pos.line_number, pii_type,
                     scan_document[ent.start:ent.end], line_text[:200])
                )

        is_bad = (action == "KEPT" and ground_truth == "FP") or (
            action == "DROP" and ground_truth == "TP"
        )
        flag = (
            "  <-- FP-survivor" if (action == "KEPT" and ground_truth == "FP")
            else ("  <-- TP-loss" if (action == "DROP" and ground_truth == "TP") else "")
        )
        (log.warning if is_bad else log.info)(
            "[%s line=%d %s/%s] %s | %s | %r @%d:%d score=%.2f%s",
            model_id, line_pos.line_number, pii_type, annotation.verdict,
            action, ground_truth, scan_document[ent.start:ent.end],
            ent.start, ent.end, float(ent.score), flag,
        )

    # --- 4. FN: TP lines GLiNER2 missed entirely -----------------------
    for ann in annotations:
        if ann.verdict != "TP":
            continue
        bucket = metrics.per_type[ann.pii_type]
        if ann.line_number not in matched_tp_lines_baseline:
            metrics.baseline_fn += 1
            bucket["b_fn"] += 1
            if ann.line_number not in matched_tp_lines_judged:
                metrics.judged_fn += 1
                bucket["j_fn"] += 1

    # --- 5. Document-wide + per-type summary ---------------------------
    log.info(
        "[document|%s] baseline tp=%d fp=%d fn=%d FP_rate=%.3f recall=%.3f "
        "| judged tp=%d fp=%d fn=%d FP_rate=%.3f recall=%.3f",
        model_id,
        metrics.baseline_tp, metrics.baseline_fp, metrics.baseline_fn,
        metrics.baseline_fp_rate, metrics.baseline_recall,
        metrics.judged_tp, metrics.judged_fp, metrics.judged_fn,
        metrics.judged_fp_rate, metrics.judged_recall,
    )
    for pii_type in sorted(metrics.per_type):
        b = metrics.per_type[pii_type]
        log.info(
            "[type=%s|%s] baseline tp=%d fp=%d fn=%d | judged tp=%d fp=%d fn=%d",
            pii_type, model_id,
            b["b_tp"], b["b_fp"], b["b_fn"], b["j_tp"], b["j_fp"], b["j_fn"],
        )
    if metrics.fp_survivors:
        log.warning(
            "[document|%s] FP-survivors (%d): %s", model_id, len(metrics.fp_survivors),
            "; ".join(
                f"line={ln} {tp}: {val!r}"
                for ln, tp, val, _ in metrics.fp_survivors[:10]
            ),
        )
    if metrics.tp_loss:
        log.warning(
            "[document|%s] TP-loss (%d): %s", model_id, len(metrics.tp_loss),
            "; ".join(
                f"line={ln} {tp}: {val!r}"
                for ln, tp, val, _ in metrics.tp_loss[:10]
            ),
        )

    # --- 6. Soft signals + hard gates ----------------------------------
    if metrics.judged_fp_rate > WARN_FP_RATE_WITH_JUDGE:
        log.warning(
            "[document|%s] judged FP_rate=%.3f above the soft cap %.2f "
            "(baseline=%.3f) — detector precision signal.",
            model_id, metrics.judged_fp_rate, WARN_FP_RATE_WITH_JUDGE,
            metrics.baseline_fp_rate,
        )
    if metrics.judged_recall < MIN_RECALL:
        log.warning(
            "[document|%s] judged recall=%.3f below soft floor %.2f "
            "(baseline=%.3f) — detector-level gap, not a judge defect.",
            model_id, metrics.judged_recall, MIN_RECALL, metrics.baseline_recall,
        )
    if metrics.recall_degradation > MAX_RECALL_DEGRADATION:
        # SOFT on the document (unlike the per-type harness): the document-wide
        # recall is distorted by the one-value-per-line annotation (GLiNER2 also
        # finds real PII the sidecar doesn't list, inflating FP and the apparent
        # TP-loss) and by values the document frames as test/example data that
        # the judge rightly discounts. So recall erosion here measures the
        # fixture+detector interaction, not a judge safety defect.
        log.warning(
            "[document|%s] judge eroded recall by %.3fpp (%.3f -> %.3f), above "
            "the %.2fpp budget — SOFT on the document (annotation granularity / "
            "test-framed values). First TP-loss: %s",
            model_id, metrics.recall_degradation, metrics.baseline_recall,
            metrics.judged_recall, MAX_RECALL_DEGRADATION,
            "; ".join(f"line={ln} {tp}: {val!r}" for ln, tp, val, _ in metrics.tp_loss[:5]),
        )

    # The only HARD gate document-wide: the judge must not WORSEN precision.
    # It removes entities only, so a regression means it dropped TPs faster than
    # FPs. Both checkpoints satisfy this (the judge is a strong precision
    # booster); absolute FP, recall floor and recall degradation are SOFT.
    assert metrics.judged_fp_rate <= metrics.baseline_fp_rate + 1e-9, (
        f"[{model_id}] judge WORSENED the document FP rate "
        f"({metrics.baseline_fp_rate:.3f} -> {metrics.judged_fp_rate:.3f}): it "
        f"removed true positives faster than false ones. First TP-loss lines: "
        + "; ".join(
            f"line={ln} {tp}: {val!r}" for ln, tp, val, _ in metrics.tp_loss[:3]
        )
    )


# ---------------------------------------------------------------------------
# Meta-test: document parses (independent of GLiNER2 and LM Studio)
# ---------------------------------------------------------------------------


def test_Should_ParseDocumentWithTpAndFp_When_AnnotationsLoaded():
    """Sanity check that runs in any venv: the document + sidecar parse and
    carry both TP and FP annotated lines."""
    scan_document, annotations, positions = _parse_document(
        GLINER2_DOCUMENT_PATH, GLINER2_ANNOTATIONS_PATH
    )
    assert scan_document, "scan_document must not be empty"
    assert len(annotations) == len(positions)
    per_verdict: Dict[str, int] = defaultdict(int)
    for ann in annotations:
        per_verdict[ann.verdict] += 1
    assert per_verdict["TP"] > 0 and per_verdict["FP"] > 0, (
        f"document must contain both TP and FP lines (got {dict(per_verdict)})"
    )
    log.info(
        "[meta] %d annotated lines (%d TP / %d FP)",
        len(annotations), per_verdict["TP"], per_verdict["FP"],
    )
